#!/usr/bin/env bash
# Update framework components within BMAD-CC repository

set -e

# Color codes
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
GRAY='\033[0;90m'
NC='\033[0m'

echo -e "${CYAN}🔄 BMAD-CC Framework Update${NC}"

# Update version in package files if they exist
if [ -f "package.json" ]; then
    echo -e "${GRAY}Updating package.json version...${NC}"
    # Update timestamp in package.json description or version
fi

# Update template versions
find templates -name "*.tmpl" -exec sed -i 's/Generated by BMAD.*/Generated by BMAD Framework v$(date +%Y.%m.%d)/g' {} \; 2>/dev/null || true

echo -e "${GREEN}✅ Framework updated${NC}"